server:
  port: 8001 # 项目端口

#dubbo:
#  application:
#    name: sakura-service
#  registry:
#    address: nacos://127.0.0.1:5201
#  scan:
#    base-packages: com.sakura.service.impl
#  protocols:
#    dubbo:
#      name: dubbo
#      port: 20880

