server:
  port: 8300

dubbo:
  application:
    name: sakura-http
  registry:
    address: nacos://127.0.0.1:4399?username=nacos&password=nacos
  qos:
    port: 20880
  metadata-report:
    address: nacos://127.0.0.1:4399?username=nacos&password=nacos

